gearuplead/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("services/",include("services.urls")),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    path("",views.index,name='home'),
    path("contact-us",views.contact,name="contact-us"),
    path("about-us",views.about_us,name="about-us"),
    path("blog",views.BlogList.as_view(),name="blog"),
    path("write_for_us",views.write_for_us,name="write_for_us"),
    path("job_opening",views.job_opening,name="job_opening"),
    path("referral_program",views.referral_program,name="referral_program"),
    path("<int:pk>/<slug>",views.blog_view,name="blog-detail"),
]   

            

home/models.py
from django.db import models
from tinymce import HTMLField
from django.template.defaultfilters import slugify
# Create your models here.
class Home_Contact_Booking_contents(models.Model):
    heading = models.CharField(max_length=100)
    content = HTMLField()

    def __str__(self):
        return self.heading

class Home_Contact_Booking(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    number = models.CharField(max_length=15)
    message = models.TextField()
    def __str__(self):
        return self.name




class Home_section_1(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=100)
    background_image = models.FileField(upload_to="home/",null=True,blank=True)

    def __str__(self):
        return self.heading

class Home_section_2(models.Model):
    heading = models.CharField(max_length=50)
    def __str__(self):
        return self.heading

class Home_section_2_card(models.Model):
    section_2 = models.ForeignKey(Home_section_2,on_delete=models.CASCADE)
    image = models.FileField(upload_to="icon/")
    title = models.CharField(max_length=30)
    description = models.TextField()

class Manage_service(models.Model):
    service_name = models.CharField(max_length=20)
    service_price_text = models.CharField(max_length=20)
    def __str__(self):
        return self.service_name

class Service_text(models.Model):
    service = models.ForeignKey(Manage_service,on_delete=models.CASCADE)
    text = models.CharField(max_length=60)

class Why_Choose_us(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=100)
    url = models.URLField(blank=True)
    def __str__(self):
        return self.heading
class Why_Choose_us_text(models.Model):
    us = models.ForeignKey(Why_Choose_us,on_delete=models.CASCADE)
    text = models.CharField(max_length=150)
    
class Our_client(models.Model):
    heading = models.CharField(max_length=50)
    def __str__(self):
        return self.heading
class Client_detail(models.Model):
    client = models.ForeignKey(Our_client,on_delete=models.CASCADE)
    client_name = models.CharField(max_length=90)
    client_image = models.FileField(upload_to="client/")


class Home_section_last(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=50)
    image = models.FileField(upload_to="home")
    def __str__(self):
        return self.heading
class Home_section_last_text(models.Model):
    last_section = models.ForeignKey(Home_section_last,on_delete=models.CASCADE)
    text = models.CharField(max_length=90)
    
class Contact_us(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    number = models.CharField(max_length=15)
    message = models.TextField()
    def __str__(self):
        return self.name +" "+self.email

class About_us(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
class About_us_section(models.Model):
    parent = models.ForeignKey(About_us,on_delete=models.CASCADE)
    heading = models.CharField(max_length=50)
    description = HTMLField()
    image = models.FileField(upload_to="about/")


class Blog(models.Model):
    heading = models.CharField(max_length=200,help_text="maximun, 200 words")
    author_name = models.CharField(max_length=30,help_text="maximum 30 words") 
    date = models.DateTimeField(auto_now=True,editable=False) 
    description = HTMLField()
    meta_description = models.TextField(help_text="Minimum 100 Words",)
    add_to_feature_post = models.BooleanField(default=False) #done
    publish_now = models.BooleanField(default=True) 

    slug = models.SlugField(null=True,blank=True,editable=False)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.heading)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.heading

class Write_about_us(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20) 
    date = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to="write_us/")
    description = models.TextField(max_length=500)
    show = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name
    
    @staticmethod
    def write_us_get():
        return Write_about_us.objects.all()
    
    class Meta:
        ordering = ("-date",)

class FAQ(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField()

    def __str__(self):
        return self.question

home/views.py
from django.shortcuts import render,redirect
from django.core.files.storage import FileSystemStorage
from .models import (
    Contact_us,
    Blog,
    Home_section_1,
    Home_section_2,
    Home_section_last,
    Why_Choose_us,
    Our_client,
    Manage_service,
    About_us,
    Write_about_us,
    FAQ,
    Home_Contact_Booking,
    Home_Contact_Booking_contents
)
from django.views.generic import ListView
from django.contrib import messages

from careers.models import Career
# Create your views here.
def index(request):
    section1 = Home_section_1.objects.first()
    section2 = Home_section_2.objects.first()
    section3 = Manage_service.objects.all()[:3]
    section4 = Why_Choose_us.objects.first()
    section5 = Our_client.objects.first()
    section6 = Home_section_last.objects.first()
    HomeBooking = Home_Contact_Booking_contents.objects.first()
    faqs = FAQ.objects.all()
    # print(section1.heading)

    
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        number = request.POST["number"]
        message = request.POST["message"]
        print(type(number))
        Home_Contact_Booking.objects.create(name=name,email=email,number=number,message=message).save()
        messages.success(request,'Your message is saved please do not submit again, We will Contact You Soon!')
        return redirect("home")





    return render(request,"home.html",{
        "section1" : section1,
        "section2" : section2,
        "section3" : section3,
        "section4" : section4,
        "section5" : section5,
        "section6" : section6,
        "faqs" : faqs,
        "HomeBooking" : HomeBooking,
    })

class BlogList(ListView):
    queryset = Blog.objects.filter(publish_now=True).exclude(add_to_feature_post=True)
    template_name = "blog.html"
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        featured_blog = Blog.objects.filter(add_to_feature_post=True).order_by("-id")[:3]
        # print(featured_blog)
        context['featured_blog'] = featured_blog
        return context
def blog_view(request,pk,slug):
    blog = Blog.objects.get(id=pk)

    return render(request,"blog-detail.html",{"blog":blog})

def contact(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        number = request.POST["number"]
        message = request.POST["message"]
        print(type(number))
        Contact_us.objects.create(name=name,email=email,number=number,message=message).save()
        messages.success(request,'Your message is saved please do not submit again withen 24 hour contact you !')
        return redirect("contact-us")
    return render(request,"contact-us.html")

def about_us(request):
    about = About_us.objects.first()
    return render(request,"about-us.html",{
        'about':about
    })


def write_for_us(request):
    
    write_data = Write_about_us.objects.filter(show=True)
    
    if request.method == 'POST':
        first_name =  request.POST['first_name']
        last_name =  request.POST['last_name']
        
        image =  request.FILES['image']
        description = request.POST['description']
        messages.success(request,'Your feedback is saved please do not submit again')
        fs = FileSystemStorage()
        myfile = fs.save("write_us/" +image.name , image)
        
        # print(fs.url(myfile))

        write_us = Write_about_us(first_name=first_name,last_name=last_name,image="write_us/" +image.name, description=description)
        write_us.save()
        return redirect("write_for_us")

    return render(request,'write-for-us.html',{'write_data':write_data})



def job_opening(request):
    return render(request,'job-opening.html',{
        "careers": Career.objects.all()
    })


def referral_program(request):
    return render(request,'referral-program.html')

home/templates/blog-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{blog.heading}} | GearUpLead{% endblock title %}
{% block navID %}{% endblock navID %}
{% block desc %}
{{blog.meta_description}}
{% endblock desc %}
{% block style %}
<link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
{% endblock style %}
{% block content %}
<section>
    <div class="bg-primary py-5">
        <div class="container">
            <h1 class="text-light text-capitalize"> <b> {{blog.heading}}</b></h1>
            <!-- <small class="text-light"> {{blog.date}}</small>    -->
        </div>
        
    </div>
    <div class="container">
        <div class="row mt-1">
            <div class="col-md-8 mx-auto overflow-auto">
                
                <!-- <h4>{{blog.heading}}</h4>
                <small class="pt-5">{{blog.author_name}}</small><br>
                <small class="pt-5"> {{blog.date}}</small> -->
                <p class="pt-4">
                    <!-- <svg class="text-dark" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                    <svg class="text-dark" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                    <svg class="text-dark" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-star-half" viewBox="0 0 16 16">
                        <path d="M5.354 5.119L7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.55.55 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.519.519 0 0 1-.146.05c-.341.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.171-.403.59.59 0 0 1 .084-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027c.08 0 .16.018.232.056l3.686 1.894-.694-3.957a.564.564 0 0 1 .163-.505l2.906-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.002 2.223 8 2.226v9.8z"/>
                    </svg> -->
                </p>
                <p class="pt-4 overflow-auto w-100">{{blog.description|safe}}</p>
                
             <br> <h5 class="font-italic text-muted text-capitalize">~{{blog.author_name}}</h5><br>
                
            </div>
        </div>
    </div>
</section>
<script src="{% static "tinymce/js/prism.js" %}"></script>
{% endblock content %}

home/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gear Up Lead | Blog{% endblock title %}
{% block navID %}blogNav{% endblock navID %}
{% block style %}
{% endblock style %}
{% block content %}
 
<section class="bg-primary w-100" style="position: absolute; padding-bottom:70px;padding-top:30px;">
    <div class="container">
        <h1 class="text-light " style="padding-top: 40px;font-weight:600;" >Featured posts</h1>
        <hr class="w-25" style="border-bottom: 4px solid rgb(245, 245, 245);">
    </div>
</section>

<section style="position: relative; padding-top:190px;">
    <div class="container">
        <div class="row">
            {% for blog in featured_blog %}
                <div class="col-md-3  card mx-auto p-3 shadow" style="border-radius:10px">
                    <a class=" text-decoration-none" href="{% url 'blog-detail' blog.id  blog.slug %}"> 
                        <div class="card-body">
                            <h5 class="card-title font-weight-bold pt-4 text-dark">{{blog.heading}}</h5>
                            <p class="card-text text-dark">{{blog.description|safe|striptags|truncatewords:20}}</p>
                            <p>
                                <small>{{blog.author_name}}</small>
                            </p>
                            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                        </div>
                    </a>
                </div>
            {%endfor%}
        </div>
    </div>
</section>

<section class="pt-5">
    <div class="container">
        <div class="row mt-5">
            <h2 class="ml-lg-3" >More posts</h2>
            <!-- <div class="col-md-4 mx-auto">
                <hr class="w-50" style="border-bottom: 4px solid rgba(0,0,0,1);">
                <div class="row m-lg-5">
                    <div class="col-md-11">
                        <div class="list-group">
                            <button type="button" class="list-group-item list-group-item-action">Dapibus ac facilisis in</button>
                            <button type="button" class="list-group-item list-group-item-action">Morbi leo risus</button>
                            <button type="button" class="list-group-item list-group-item-action">Porta ac consectetur ac</button>
                            <button type="button" class="list-group-item list-group-item-action" disabled>Vestibulum at eros</button>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="col-md-8 mx-auto">
                {% for blog in object_list %} 
                <div class="card mt-4 bg-light p-3 " >
                    <a class=" text-decoration-none" href="{% url 'blog-detail' blog.id blog.slug %}">
                        <div class="card-body">  
                            <h5 class="card-title text-dark">{{blog.heading}}</h5>
                            <p class="card-text text-dark">{{blog.description|safe|striptags|truncatewords:50}}</p>
                            <p>
                                <small>{{blog.author_name}} {{blog.date}}</small>
                            </p>
                        </div>
                    </a>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</section>




{% endblock content %}

home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Generate leads free | GearUplead{% endblock title %}
{% block navID %}homeNav{% endblock navID %}
{% block style %} 
{% endblock style %}
<style>
    @media only screen and (min-width: 200px)
    {
    .dropdown:hover>.dropdown-menu
    {
    display: block;
    }

    }
</style>
{% block content %}
<section class="home_section" style="background-image: url('{%if section1.background_image %}{{section1.background_image.url}}{%else%}{%endif%}');">
    <div class="" style="width: 100%; height:85vh; background-color:rgba(0,0,0,0.5);">
        <div class="container" style="font-family: sans-serif;">
            <h1 class="text-white" style="padding-top: 150px;" id="textHeader" >{{section1.heading}}</h1>
            <p class="text-white pt-4" id="textSubHeader" >{{section1.sub_heading}} <span1></span1></p>
            <div class="text-left mt-5">
                <a href="{%url 'contact-us' %}" class="btn btn-primary rounded-pill btn-lg mr-2 mt-3">Get Start Today</a>
                <a href="{%url 'services' %}" class="btn btn-outline-light rounded-pill btn-lg mt-3">Know more</a>
            </div>

        </div>
    </div>
</section>

<section>
    <div class="container  pt-5">
        <h2 class="text-capitalize text-center container pt-3 col-md-8" style="color: #2e4862;">
            <!-- What Is Gearuplead Relation Ship And How to we Help A <br> People for businees         -->
            <span>
                {{HomeBooking.heading}}

            </span>
        </h2>
        <hr class="mx-auto mt-4" style="border-bottom: 4px solid ; width:10%;">
        <div class="row mx-auto align-items-center">
            <div class="pt-5 col-md-6">
                {{HomeBooking.content|safe}}
                <!-- <h3 class=" text-capitalize" style="color: #2e4862;">A Trusted Gear Up Lead Relation Ship Services Company</h3> 
                <h5 class="pt-4 text-capitalize" style="color: #6e6e6e;">Our Full Funnel Lead generation and appointment setting solutions are capable of generating:</h5>   
                <p class="pt-4 text-capitalize" style="color: #6e6e6e;font-size:18px;">when it comes to the gear up lead Relatiion Ship service we understand that both value and quality of the lead and we are highly important. gear up lead use and search the marketing comppnies data and then collect the data of company then after that we are serve the west business of the buyers. the gear up lead delivered are the 100% qualified and 100% opted in.</p>
                
                <ul class="pt-4" style="color: #2e4862;font-size:18px;">
                    <li>Business Qualified Leads</li>
                    <li>Marketing Qualified Leads</li>
                    <li>Sales Qualified Leads</li>
                    <li>Marketing Qualified Leads </li>
                </ul>
                <p pclass="pt-5 text-capitalize" style="color: #6e6e6e;font-size:18px;">Find, Engage, & Close Your right Fit Accounts.
                    Identify people with the right job titles from accounts who are actively researching your products and solutions.
                </p>
                <h5 class="pt-4 text-capitalize" style="color: #6e6e6e;">We Are Proud of What We Have Achieved:</h5>
                <p class="pt-5 text-capitalize" style="color: #6e6e6e;font-size:18px;">Among The top Marketing Technology Solution providers according to gearuplead.com
                </p>
                <p class="text-capitalize" style="color: #6e6e6e;font-size:18px;">GearUpLead has been the best in class in providing the Lead Relation ship services for tech companies
                </p> -->
            </div>
            <div class="col-md-6 p-lg-5">
                <form class=" shadow" action="" method="POST">{% csrf_token %}
                    <div class="p-5">
                        <h4 style="color: #2e4862; font-size:30px;">Let’s Discuss More About Your Business Needs!</h4>
                        <p class="pt-3" style="color: #2e4862;"><svg  xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone-forward-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zm10.761.135a.5.5 0 0 1 .708 0l2.5 2.5a.5.5 0 0 1 0 .708l-2.5 2.5a.5.5 0 0 1-.708-.708L14.293 4H9.5a.5.5 0 0 1 0-1h4.793l-1.647-1.646a.5.5 0 0 1 0-.708z"/>
                          </svg> Call 
                          <a href="tel:+917795724941">+91-7795724941</a>
                          
                        </p>
                          
                          <div class="form-group pt-4">
                            <label style="color: #2e4862; font-size:18px;" class="" for="exampleInputEmail1"> <b>Name</b></label>
                            <input type="text" name="name" class="form-control shadow-none pt-2" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                          </div>
                          <div class="form-group pt-3">
                            <label style="color: #2e4862; font-size:18px;" class="" for="exampleInputEmail1"> <b> Email address</b></label>
                            <input type="email" name="email" class="form-control shadow-none pt-2" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                          </div>
                          <div class="form-group pt-3">
                            <label style="color: #2e4862; font-size:18px;" class="" for="exampleInputEmail1"> <b>Contact number</b></label>
                            <input type="text" name="number" class="form-control shadow-none pt-2" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                          </div>
                          <div  class="form-group pt-3">
                            <label style="color: #2e4862; font-size:18px;" for="exampleFormControlTextarea1"> <b> Tell us more about your needs: </b></label>
                            <textarea class="form-control shadow-none" name="message" id="exampleFormControlTextarea1" rows="3" required></textarea>
                          </div>
                          <p class="pt-4">
                              <button type="submit" class="btn btn-outline-success btn-lg btn-block">Book a trial</button>
                          </p>
                    </div>
                   
                </form>
            </div>
        </div>
    </div>
</section>


<section  >
    <div class="m-3">
        <h1 class="text-center p-5 mt-4" style="font-family: sans-serif;color: #2e4862;">
            {{section2}}
        </h1>
        <div class="row">
            {% for sec in section2.home_section_2_card_set.all %} 
                <div class="col-md-6 mt-2 mx-auto pl-2 pt-2">
                    <div class="card shadow p-4 showCard w-100 h-100">
                   
                    <i class="fa fa-quote-left" style="font-size:15px;color:width"></i>
                    
                    <p class="text-center">
                        <img class="text-center rounded-circle" src="{{sec.image.url}}" style="object-fit: cover;height: 4rem;width: 4rem; padding: 2px;" alt="">
                    </p>
                    <h6 class="pt-2 text-center" style="color: #2e4862;font-size:20px;">{{sec.title}}</h6>
                    <small class="pt-2 text-center" style="color: #6e6e6e; font-size:18px;">{{sec.description}}</small>
                    <span><i class="fa fa-quote-right float-right" style="font-size:15px;color:width"></i></span>
                    
                </div>
                    <!-- <p class="pt-3">
                        <span style="display: inline;" id="less-{{forloop.counter}}">{{sec.description|safe|striptags|truncatechars:100}}</span>
                        <span style="display: inline;" id="dots-{{forloop.counter}}">...</span>
                        <span style="display: none;" id="more-{{forloop.counter}}">{{sec.description|safe}}</span>
                        <small id="read" onclick="read()">read more</small>
                    </p>
                    <p class=""><button type="button" id="read-{{forloop.counter}}" onclick="read('{{forloop.counter}}')" class="btn btn-outline-primary rounded-pill my-4">read more </button></p> -->
                </div >
            {%endfor%}
        </div>
    </div>
    
</section>


<section class="bg-primary my-5">
    <div class="container p-2">
        <h1  class="mt-3 text-center text-light" style="color: #2e4862;">Our Services</h1>
        <div class="row my-5 " >
            {% for ser in section3 %}
            <div class="col-md-4 our_section">
                <div class="card mt-2">
                <h4 class="text-center p-4" >{{ser.service_name}}</h4>
                <ul id="our-serivice-list">
                    {% for text in ser.service_text_set.all%}
                        <li>{{text.text}}</li>
                    {%endfor%}
                </ul>
                <p class="text-center p-4"><a href="/contact-us" class="btn btn-primary btn-lg btn-block">{{ser.service_price_text}}</a></p>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</section>

<section class="container" style="width:100%;">
    <div class="row  align-items-center">
        <div class="col-12 text-center">
            <h1 style="color: #2e4862;">Why Choose US</h1>
        </div>
        <div class="col-md-5">
            <img src="{% static 'images/cropped-growth-1953662_1280.jpg' %}" alt=" " width="100%" height="100%">
        </div>
        <div class="col-1"></div>
        <div class="col-md-5">
            <h1 class="mb-5" style="color: #2e4862;"> <b>{{section4.heading }}</b> </h1>
            <h5 class="my-4" style="color: #6e6e6e;">{{section4.sub_heading}}</h5>
            <ol>
                {% for text in section4.why_choose_us_text_set.all %}
                <li style="color: #6e6e6e;font-size:18px;">{{text.text}}</li>
                {%endfor%}
            </ol>
            <div>
                <a href="{{section4.url}}" class="btn btn-outline-primary rounded-pill btn-lg my-4">Load More </a>
            </div>
        </div>
    </div>
</section>

<section class="mb-5" style="width: 100%;background-color:rgb(216, 216, 216); ">
    <div class="container mb-5">
        <h1 class="text-center pt-5" style="color: #2e4862;">{{section5.heading}}</h1>
        <div class="row pb-5 pt-4">
            {%for client in section5.client_detail_set.all %}
            <div class="col-md-2 card shadow mt-3 mr-3 py-5"> 
                <img src="{{client.client_image.url}}" alt="" width="100%" height="100%" style="object-fit: cover;">
            </div>
                {%endfor%}
        </div>
    </div>
</section>
<section>
    <div class="container mt-5" style="width: 100%;">
        <div class="row mt-5">
            <div class="col-md-6">
                <a class="text-decoration-none pt-5" href="#" style="color: #2e4862;"><h1>{{section6.heading}}</h1></a>
                <h4 class="mt-5 text-dark" style="color: #2e4862;">{{section6.sub_heading}}</h4>
                <ul class="mt-4">
                    {%for text in section6.home_section_last_text_set.all %}
                    <li style="color: #6e6e6e;font-size:18px;"> {{text.text}} </li>
                    {%endfor%}
                </ul>
            </div>
            <div class="col-md-6 overflow-hidden p-0" >
                <img src="{{section6.image.url}}" class="grow" width="100%" height="100%" alt="">
            </div>
        </div>
    </div>
</section>

<style>
    .porinter{
        cursor: pointer;
    }
</style>

<div class="py-5"></div>

{%include 'roi.html' %}


<section class=" book_section">
    <div class="container col-md-8">
        <h1 class="text-center p-5" style="color: #2e4862;">F A Q</h1>
        <div class="accordion" id="accordionExample">
            {% for faq in faqs %}   
            <div class="porinter">
              <div class="" id="heading{{forloop.counter}}">
                <h4 class="mb-0 ml-4">
                  <span class=" text-left "  data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapse{{forloop.counter}}">
                      {{faq.question}}
                      <svg class=" float-right" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </span>
                </h4>
            </div>
            <div id="collapse{{forloop.counter}}" class="collapse " aria-labelledby="heading{{forloop.counter}}" data-parent="#accordionExample">
                <div class="card-body" >
                    <p>{{faq.answer}}</p>
                </div>
              </div>
            </div>
            <hr style="border-bottom: 3px solid rgb(0, 102, 255);">
            {%endfor%}
          </div>        
    </div>
</section>



{% endblock content %}

    