gearuplead/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("services/",include("services.urls")),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    path("",views.index,name='home'),
    path("contact-us",views.contact,name="contact-us"),
    path("about-us",views.about_us,name="about-us"),
    path("blog",views.BlogList.as_view(),name="blog"),
    path("write_for_us",views.write_for_us,name="write_for_us"),
    path("job_opening",views.job_opening,name="job_opening"),
    path("referral_program",views.referral_program,name="referral_program"),
    path("<int:pk>/<slug>",views.blog_view,name="blog-detail"),
]   

            

services/urls.py
from django.urls import path,include
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    path("",views.services,name="services"),
    path("core",views.core_services,name="core_services"),
]

home/models.py
from django.db import models
from tinymce import HTMLField
from django.template.defaultfilters import slugify
# Create your models here.
class Home_Contact_Booking_contents(models.Model):
    heading = models.CharField(max_length=100)
    content = HTMLField()

    def __str__(self):
        return self.heading

class Home_Contact_Booking(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    number = models.CharField(max_length=15)
    message = models.TextField()
    def __str__(self):
        return self.name




class Home_section_1(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=100)
    background_image = models.FileField(upload_to="home/",null=True,blank=True)

    def __str__(self):
        return self.heading

class Home_section_2(models.Model):
    heading = models.CharField(max_length=50)
    def __str__(self):
        return self.heading

class Home_section_2_card(models.Model):
    section_2 = models.ForeignKey(Home_section_2,on_delete=models.CASCADE)
    image = models.FileField(upload_to="icon/")
    title = models.CharField(max_length=30)
    description = models.TextField()

class Manage_service(models.Model):
    service_name = models.CharField(max_length=20)
    service_price_text = models.CharField(max_length=20)
    def __str__(self):
        return self.service_name

class Service_text(models.Model):
    service = models.ForeignKey(Manage_service,on_delete=models.CASCADE)
    text = models.CharField(max_length=60)

class Why_Choose_us(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=100)
    url = models.URLField(blank=True)
    def __str__(self):
        return self.heading
class Why_Choose_us_text(models.Model):
    us = models.ForeignKey(Why_Choose_us,on_delete=models.CASCADE)
    text = models.CharField(max_length=150)
    
class Our_client(models.Model):
    heading = models.CharField(max_length=50)
    def __str__(self):
        return self.heading
class Client_detail(models.Model):
    client = models.ForeignKey(Our_client,on_delete=models.CASCADE)
    client_name = models.CharField(max_length=90)
    client_image = models.FileField(upload_to="client/")


class Home_section_last(models.Model):
    heading = models.CharField(max_length=50)
    sub_heading = models.CharField(max_length=50)
    image = models.FileField(upload_to="home")
    def __str__(self):
        return self.heading
class Home_section_last_text(models.Model):
    last_section = models.ForeignKey(Home_section_last,on_delete=models.CASCADE)
    text = models.CharField(max_length=90)
    
class Contact_us(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    number = models.CharField(max_length=15)
    message = models.TextField()
    def __str__(self):
        return self.name +" "+self.email

class About_us(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
class About_us_section(models.Model):
    parent = models.ForeignKey(About_us,on_delete=models.CASCADE)
    heading = models.CharField(max_length=50)
    description = HTMLField()
    image = models.FileField(upload_to="about/")


class Blog(models.Model):
    heading = models.CharField(max_length=200,help_text="maximun, 200 words")
    author_name = models.CharField(max_length=30,help_text="maximum 30 words") 
    date = models.DateTimeField(auto_now=True,editable=False) 
    description = HTMLField()
    meta_description = models.TextField(help_text="Minimum 100 Words",)
    add_to_feature_post = models.BooleanField(default=False) #done
    publish_now = models.BooleanField(default=True) 

    slug = models.SlugField(null=True,blank=True,editable=False)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.heading)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.heading

class Write_about_us(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20) 
    date = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to="write_us/")
    description = models.TextField(max_length=500)
    show = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name
    
    @staticmethod
    def write_us_get():
        return Write_about_us.objects.all()
    
    class Meta:
        ordering = ("-date",)

class FAQ(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField()

    def __str__(self):
        return self.question

services/models.py
from django.db import models
from tinymce.models import HTMLField
# from tinymce import TinyMCE
class Service(models.Model):
    heading = models.CharField(max_length=100)
    sub_heading = models.CharField(max_length=100)
    is_core = models.BooleanField(default=False)
    def __str__(self):
        return self.heading

class ServiceSection(models.Model):
    parent = models.ForeignKey(Service,on_delete=models.CASCADE)
    heading = models.CharField(max_length=100)
    content = HTMLField()
    image = models.FileField(upload_to="service/")
    

services/views.py
from django.shortcuts import render,HttpResponse
from .models import Service
# Create your views here.
from home.models import Our_client

def services(request):
    section5 = Our_client.objects.first()
    services = Service.objects.filter(is_core=False)
    return render(request,'service.html',{
        "service" : services[0] if services else None,
        "section5" : section5
    })
def core_services(request):
    section5 = Our_client.objects.first()
    services = Service.objects.filter(is_core=True)
    
    return render(request,'service.html',{
        "service" : services[0] if services else None,
        "section5" : section5
    })

services/templates/service.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gear Up Lead | Service{% endblock title %}
{% block navID %}serviceNav{% endblock navID %}
{% block style %}{% endblock style %}
{% block content %}

<section class="service">
    <div class="service_div">
        <div class="container pt-5">
            <h1 class=" text-center text-light pt-5 font-weight-bold">{{service}}</h1>
            <h3 class="text-center pt-4 text-primary">{{service.sub_heading}}</h3>
            <hr class="mx-auto" style="border-bottom: 4px solid rgb(226, 226, 226); width:5%;">
        </div>
    </div>
</section>
{%for ser in service.servicesection_set.all %}
{%if forloop.counter|divisibleby:"2" %}
<section class="" style="margin-top: 100px;"> 
    <div class="container">
        <div class="row">
            <div class="col-md-4 overflow-hidden">
                <img class=" img-responsive img-thumbnail" src="{{ser.image.url}}" alt="" style="border: none;">  
            </div>
            <div class="col-md-7 d-flex justify-content-around p-5" style="margin-top: 20px;">
                <div>
                    <h2>{{ser.heading}}</h2>
                    <hr class="w-25" style="border-bottom: 4px solid rgb(20, 161, 255);">
                    <p class="pt-4">{{ser.content|safe}}</p>
                </div>
                <div></div>
            </div>
        </div>
    </div>
</section>
{%else%}
<section class="" style="margin-top: 100px;">
    <div class="container">
        <div class="row">
            <div class="col-md-7 p-5" style="margin-top: 20px;">
                <h2>{{ser.heading}}</h2>
                <hr class="w-25" style="border-bottom: 4px solid rgb(20, 161, 255);">
                <p class="pt-4" style="text-align: justify;text-justify: inter-word !important;">
                    {{ser.content|safe}}
                </p>
            </div>
            <div class="col-md-4">
                <img class="img-responsive img-thumbnail " src="{{ser.image.url}}" alt="" style="border: none;">
            </div>
        </div>
    </div>
</section>
{%endif%}
{%endfor%}

<section class="mt-5 pb-4" style="width: 100%;background-color:rgb(216, 216, 216); ">
    <div class="container mb-5">
        <h1 class="text-center pt-5">{{section5.heading}}</h1>
        <div class="row pb-5 pt-4">
            {%for client in section5.client_detail_set.all %}
            <div class="col-md-2 card shadow mt-3 mr-3 py-5"> 
                <img class="img-responsive img-thumbnail w-100 h-100" src="{{client.client_image.url}}" alt="">
            </div>
                {%endfor%}
        </div>
    </div>
</section>


{% endblock content %}